import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0
