import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"

[font]
normal = "JetBrainsMono Nerd Font"
size = 14.0
