import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"
